/*
 * cpsc2_debugfs.c
 *
 *  Created on: 16 Mar 2019
 *      Author: pgm
 */


#include "cpsc2.h"
#include "acq400.h"
#include "acq400_debugfs.h"
#include "acq400_debugfs_internal.h"

void cpsc2_dac_createDebugfs(struct acq400_dev* adev, char* pcursor)
{
	DBG_REG_CREATE(CPSC2_DAC_SFP1_PKT_CNT);
	DBG_REG_CREATE(CPSC2_DAC_SFP1_SKIP_PKT_CNT);
	DBG_REG_CREATE(CPSC2_DAC_SFP2_PKT_CNT);
	DBG_REG_CREATE(CPSC2_DAC_SFP2_SKIP_PKT_CNT);
	DBG_REG_CREATE(CPSC2_DAC_PKT_TX);
	DBG_REG_CREATE(CPSC2_DAC_PKT_SEQ);
	DBG_REG_CREATE(CPSC2_DAC_PROC_STA);
	DBG_REG_CREATE(CPSC2_DAC_MATH_STA);

	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(1));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(2));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(3));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(4));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(5));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(6));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(7));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(8));
}
