/*
 * cpsc2_debugfs.c
 *
 *  Created on: 16 Mar 2019
 *      Author: pgm
 */


#include "cpsc2.h"
#include "acq400.h"
#include "acq400_debugfs.h"
#include "acq400_debugfs_internal.h"

void cpsc2_dac_createDebugfs(struct acq400_dev* adev, char* pcursor)
{
	DBG_REG_CREATE_NAME("SFP1_PKT_CNT", CPSC2_DAC_SFP1_PKT_CNT);
	DBG_REG_CREATE_NAME("SFP1_PKT_CNT", CPSC2_DAC_SFP1_SKIP_PKT_CNT);
	DBG_REG_CREATE_NAME("SFP1_PKT_CNT", CPSC2_DAC_SFP2_PKT_CNT);
	DBG_REG_CREATE_NAME("SFP1_PKT_CNT", CPSC2_DAC_SFP2_SKIP_PKT_CNT);
	DBG_REG_CREATE(CPSC2_DAC_PKT_TX);
	DBG_REG_CREATE(CPSC2_DAC_PKT_SEQ);
	DBG_REG_CREATE(CPSC2_DAC_PROC_ICST);
	DBG_REG_CREATE(CPSC2_DAC_MATH_ICST);

	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(1));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(2));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(3));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(4));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(5));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(6));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(7));
	DBG_REG_CREATE(CPSC2_DAC_SLOW_SET_CH(8));
	DBG_REG_CREATE(CPSC2_DAC_RTM_LENGTH);
}

void cpsc2_com_createDebugfs(struct acq400_dev* adev, char* pcursor)
{
	DBG_REG_CREATE(CPSC2_COM_CONTROL);
	DBG_REG_CREATE_NAME("HEARTBEAT", CPSC2_COM_HEARTBEAT);
	DBG_REG_CREATE(CPSC2_COM_SFP_AURORA_CR(1));
	DBG_REG_CREATE_NAME("AURORA1_STA0", CPSC2_COM_SFP_AURORA_STA(1));
	DBG_REG_CREATE_NAME("AURORA1_STA1", CPSC2_COM_SFP_AURORA_STA1(1));
	DBG_REG_CREATE_NAME("AURORA1_STA2", CPSC2_COM_SFP_AURORA_STA2(1));
	DBG_REG_CREATE(CPSC2_COM_SFP_AURORA_CR(2));
	DBG_REG_CREATE_NAME("AURORA1_STA0", CPSC2_COM_SFP_AURORA_STA(2));
	DBG_REG_CREATE_NAME("AURORA2_STA1", CPSC2_COM_SFP_AURORA_STA1(2));
	DBG_REG_CREATE_NAME("AURORA2_STA2", CPSC2_COM_SFP_AURORA_STA2(2));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(1,0));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(1,1));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(1,2));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(1,3));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(1,4));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(2,0));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(2,1));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(2,2));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(2,3));
	DBG_REG_CREATE(CPSC2_COM_LAST_PKT(2,4));
}
