#!/bin/sh


echo +++acq428.init $*  begin 01

for s in $*; do
    if [ -z $SITES ]; then
    	SITES=$s
    else
    	SITES=$SITES,$s
    fi
done

[ -e /mnt/local/sysconfig/acq400.sh ] && source /mnt/local/sysconfig/acq400.sh


ACQ428_DEFSPAN=${ACQ428_DEFSPAN:-M10-10}

MODFILE=/mnt/local/acq428_drv.ko
if [ -e $MODFILE ]; then
        echo loading override /mnt/local/acq428_drv.ko
else
	MODFILE=/usr/local/lib/modules/acq428_drv.ko
fi

/sbin/insmod $MODFILE ${ACQ428_PARAMS} acq428sites=$SITES

/sbin/insmod /lib/modules/4.14.0-acq400-xilinx/spidev.ko

/sbin/insmod /lib/modules/4.14.0-acq400-xilinx/acq400_hook_spi_cs.ko

mkdir -p /dev/acq428

D428=/dev/acq428
EK=/etc/acq400

for site in $*; do
        /usr/local/CARE/load.overlay acq428_s${site}_overlay /mnt/local/acq428_s${site}_overlay.dtb
        mkdir -p ${D428}/${site}
        echo 
done

# TODO: need this to happen for more than one site
/usr/local/CARE/acq428_adc_init 0

for site in $*; do
        ek=/etc/acq400/${site}
        dk=/dev/acq400.${site}.knobs

        echo ${ACQ428_DATA32:-0} > $dk/data32
        rm -f $ek/data32
        cat - >$ek/data32 <<EOF
#!/bin/sh
if [ "x\$1" = "x" ]; then
        cat $dk/data32
else
        echo \$1 > $dk/data32
        echo set data32
fi
EOF
        chmod a+rx $ek/data32
        ln -s /usr/local/CARE/acq428_adc.init ${ek}
#       (cd ${ek};source /tmp/makeLinks)
done

for site in $*; do
    bus=$(expr "$site" + 1)
    /usr/local/CARE/acq428gpio.init ${site} ${bus}
done

# make post job boot file
(
cat - <<EOF
#!/bin/sh
while [ ! -e  /var/www/d-tacq/rc-user-complete ]; do
	sleep 3
done
echo acq428_init.job \$(cat /var/www/d-tacq/rc-user-complete)
EOF

for site in $*; do
	echo "SITE=$site /usr/local/CARE/acq428_adc.init"
	echo "SITE=$site $ACC"
done

cat - <<'EOF'
echo run link calibration..
/usr/local/CARE/acq428_adc_init 0
/usr/local/CARE/acq428_idelay 0
echo 1 > /sys/devices/soc0/amba/40010000.acq400fmc/idelay_en
/usr/local/CARE/acq428_sync 0
echo 1 > /sys/devices/soc0/amba/40010000.acq400fmc/sync_en
/usr/local/CARE/acq428_data 0
echo checking calib_debug for ff00ff00

DEBUG_FILE="/sys/kernel/debug/acq400/acq400.1/ACQ428_CALIB_DEBUG.0x58"
PATTERN=$(cat "$DEBUG_FILE")

if [ "$PATTERN" != "0xff00ff00" ]; then
    echo "Error: Calibration pattern mismatch! Expected 0xff00ff00, got $PATTERN"
    exit 1
fi

echo Calibration good: pattern 0xff00ff00 detected.
echo 0 > /sys/devices/soc0/amba/40010000.acq400fmc/sync_en
echo 0 > /sys/devices/soc0/amba/40010000.acq400fmc/idelay_en
echo acq428_init.job 99
EOF

) >/tmp/acq428_init.job
chmod a+rx /tmp/acq428_init.job

nice /tmp/acq428_init.job &

echo +++acq428.init 99

# FPGA check for XRM
FPGA=$(grep filename /tmp/fpga_status | awk '{ print $5 }')

if echo $FPGA | grep -q '\-XRM'; then
    echo "It's an XRM!"
fi
