#!/bin/sh


echo +++acq428.init $*  begin 01

for s in $*; do
    if [ -z $SITES ]; then
    	SITES=$s
    else
    	SITES=$SITES,$s
    fi
done

[ -e /mnt/local/sysconfig/acq400.sh ] && source /mnt/local/sysconfig/acq400.sh


ACQ428_DEFSPAN=${ACQ428_DEFSPAN:-M10-10}

MODFILE=/mnt/local/acq428_drv.ko
if [ -e $MODFILE ]; then
        echo loading override /mnt/local/acq428_drv.ko
else
	MODFILE=/usr/local/lib/modules/acq428_drv.ko
fi

/sbin/insmod $MODFILE ${ACQ428_PARAMS} acq428sites=$SITES

mkdir -p /dev/acq428

D428=/dev/acq428
EK=/etc/acq400

for site in $*; do
        # /usr/local/CARE/load.overlay acq428_c32_s${site}_overlay
        mkdir -p ${D428}/${site}
        #for spidev in $SPI/spi1.*; do
        #        cb=$(printf %x ${spidev#*.})
        #        if [ ${cb:0:1} -eq $site ]; then
        #                chip=${cb:1:1}
        #                alpha=$(echo $chip | tr 01234567 ABCDEFGH)
        #                id=$chip
        #                ln -s ${D428}/$site/${id} ${D428}/$site/${alpha}
        #                direct=reg.$site.$chip
        #                ln -s ${D428}/$direct ${D428}/reg.$site.$alpha
        #                iiodev=$(cat ${spidev}/iio_id)
        #                ln -s ${IIO}${iiodev}                    ${D428}/$site/${id}
        #                ln -s ${IIOD}${iiodev}/direct_reg_access ${D428}/$direct
        #        fi
        #done

        #ch=1
        #for chip in ${D428}/${site}/[0123]; do
        #        for pchan in 7 6 5 4 3 2 1 0; do
        #                in_v=$chip/in_voltage${pchan}
        #                span=${in_v}_softspan
        #                [ ! -e $span ] && break
 
#                        ln -s $span ${EK}/${site}/gain${ch}
#                        echo $ACQ428_DEFSPAN > $span
#                        ln -s ${in_v}_scale ${EK}/${site}/scale${ch}
#                        ch=$((ch+1))
#                done
#        done
        echo 
done


for site in $*; do
        ek=/etc/acq400/${site}
        dk=/dev/acq400.${site}.knobs

        echo ${ACQ428_DATA32:-0} > $dk/data32
        rm -f $ek/data32
        cat - >$ek/data32 <<EOF
#!/bin/sh
if [ "x\$1" = "x" ]; then
        cat $dk/data32
else
        echo \$1 > $dk/data32
        echo set data32
fi
EOF
        chmod a+rx $ek/data32
        ln -s /usr/local/CARE/acq428_adc.init ${ek}
#       (cd ${ek};source /tmp/makeLinks)
done

for site in $*; do
    /usr/local/CARE/acq428gpio.init ${site} 2
done

# make post job boot file
(
cat - <<EOF
#!/bin/sh
while [ ! -e  /var/www/d-tacq/rc-user-complete ]; do
	sleep 3
done
echo acq428_init.job \$(cat /var/www/d-tacq/rc-user-complete)
EOF

for site in $*; do
	echo "SITE=$site /usr/local/CARE/acq428_adc.init"
	echo "SITE=$site $ACC"
done

cat - <<EOF
echo run link calibration..
/usr/local/CARE/acq428_calibrate_links
echo acq428_init.job 99
EOF

) >/tmp/acq428_init.job
chmod a+rx /tmp/acq428_init.job

nice /tmp/acq428_init.job &

echo +++acq428.init 99

