#!/bin/sh

SITE=${SITE:-1}

id=$(basename $0)

if [ "$id" = "gains" ]; then
	GAINS=""
	for ic in $(seq 1 16)
	do
            val=$(/etc/acq400/$SITE/gain$ic)
	    GAINS="$GAINS $val"
	done
	echo $GAINS	
	exit 0
fi
CH=${id#gain}
KNOB2=/dev/acq428/$SITE/ADC_${CH}_A2
KNOB1=/dev/acq428/$SITE/ADC_${CH}_A1
KNOB0=/dev/acq428/$SITE/ADC_${CH}_A0

set_gain() {
	set.sys $KNOB2 $1
	set.sys $KNOB1 $2
	set.sys $KNOB0 $3
}

get_gain() {
    bits=$(cat $KNOB2)$(cat $KNOB1)$(cat $KNOB0)
	case $bits in
	111) echo 16;;
	110) echo 8;;
	101) echo 4;;
	100) echo 2;;
	011) echo 1;;
	010) echo 0.5;;
	001) echo 0.25;;
	*)  echo 0.125;;
	esac
}

case $1 in
16) set_gain 1 1 1;;
8) set_gain 1 1 0;;
4) set_gain 1 0 1;;
2) set_gain 1 0 0;;
1) set_gain 0 1 1;;
0.5) set_gain 0 1 0;;
0.25) set_gain 0 0 1;;
*) get_gain;;
esac
