#!/bin/sh

SITE=${1:-0}
KNOBS=/dev/acq400.${SITE}.knobs
EK=/etc/acq400/$SITE

echo +++ initializing DACs 

ln -s /usr/local/bin/wavegen /etc/acq400/$SITE

SPANS=/sys/kernel/debug/acq400/acq400.${SITE}/spans

for spchan in ${SPANS}/??
do
	ln -s $spchan ${EK}/range$(basename $spchan)
done

INITS=/sys/kernel/debug/acq400/acq400.${SITE}/init/


for ichan in ${INITS}/??
do
	ln -s $ichan ${EK}/init$(basename $ichan)
done

ln -s ${EK}/dacreset_device ${EK}/range99
[ ! -e ${EK}/awg_seg ] && ln -s ${MODP}/awg_seg ${EK}
[ ! -e ${EK}/awg_seg_bufs ] && ln -s ${MODP}/awg_seg_bufs ${EK}

cat - <<EOF >>${EK}/groups
range=range[0-9]*
init=init[0-9]*
AO_ALL=AO_[0-9]*
EOF

