#!/bin/sh
# streams to nowhere .. get streaming!

SERVICE=nowhere
PIDF=/var/run/run.$SERVICE.pid
#LOG=/var/log/run.$SERVICE.log
LPORT=$(get-port-from-service acq4xx-$SERVICE-console)

SIGTERM=15
HATXNOEFFECT=0
start() {
		/usr/local/bin/procServ --restrict -c / -p $PIDF --killsig=-$HATXNOEFFECT $LPORT \
			/usr/local/bin/streamtonowhere
}

ACQ400_MAIN_PIDF=/var/run/acq400_stream.0.pid

stop() {
        if [ -r ${ACQ400_MAIN_PIDF} ]; then
        	echo 1 > /dev/acq400.0.knobs/estop
            kill -${SIGTERM} $(cat ${ACQ400_MAIN_PIDF})
            rm ${ACQ400_MAIN_PIDF}
			sleep 0.1
			set.site 0 state 0
        fi
}

status() {
	if [ -r ${PIDF} ]; then
		echo running $(cat ${PIDF})
	else
		echo stopped
	fi
}

case $1 in
start|"")
        start;;
stop)
        stop;;
status)
	status;;
*)
        echo "USAGE streamtonowhered  start\|stop";;
esac


